branches:
    only:
        - master

sudo: required
dist: trusty

language: python
python:
    - "2.7"
    - "3.4"

before_install:
    - sudo add-apt-repository -y ppa:reddit/ppa
    - sudo apt-get update -q
    - sudo apt-get install -y python-thrift python3-thrift fbthrift-compiler libenchant-dev python-sphinx python3-sphinx

install:
    - pip install -e .
    - python setup.py test

script: make tests
